server:
  port: 9876
  servlet:
    context-path: /ytora
spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
logging:
  config: classpath:log/logback-dev.xml
knife4j:
  enable: true
  setting:
    language: zh_cn
springdoc:
  override-with-generic-response: false
ytora:
  base-package: xyz.ytora.**
  version: @project.version@
  auth:
    enable: true
    token-invalid-time: 6000
    allow-credentials: true
    origins: http://localhost:8765
  cache:
    default-cache: local
    impl:
      local: xyz.ytora.base.cache.support.local.CacheByLocal
  storage:
    type: xyz.ytora.base.storage.support.LocalFileStorageServiceImpl
    strategy: xyz.ytora.base.storage.strategy.Murmur3_128StrategyImpl
    max: 100MB
    path: "file-storage/"
  sql4j:
    entity-path: xyz.ytora
    repo-path: xyz.ytora
    slow-sql-threshold: 3000
    sql-log-impl: xyz.ytora.base.sql4J.LogbackSqlLogger
    create-table-if-not-exist: true
    dynamic-ds:
      primary:
        desc: '主业务库'
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ytora?currentSchema=ytora&ssl=false&stringtype=unspecified
        username: ytora
        password: 220600
        type: com.zaxxer.hikari.HikariDataSource
      test:
        desc: '测试库'
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&ssl=false&stringtype=unspecified
        username: root
        password: 220600
        type: com.zaxxer.hikari.HikariDataSource