server:
  port: 9876
  servlet:
    context-path: /ytora
logging:
  config: classpath:log/logback-dev.xml
ytora:
  base-package: xyz.ytora.**
  version: @project.version@
  auth:
    enable: true
    token-invalid-time: 600
    allow-credentials: true
    origins: http://localhost:8765
  sql4j:
    entity-path: xyz.ytora
    sql-log-impl: xyz.ytora.base.sql4J.MySqlLogger
    create-table-if-not-exist: true
    dynamic-ds:
      primary:
        #连接基本信息
        driver-class-name: org.postgresql.Driver
#        url: jdbc:mysql://192.168.1.246:3306/ytor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=256&prepStmtCacheSqlLimit=2048&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
        url: jdbc:postgresql://localhost:5432/ytora
        username: ytora
        password: 220600
#        password: Mysql8@pwd
        type: com.zaxxer.hikari.HikariDataSource
