server:
  port: 9876
  servlet:
    context-path: /ytora
logging:
  config: classpath:log/logback-dev.xml
ytora:
  base-package: xyz.ytora.**
  version: @project.version@
  auth:
    enable: false
    token-invalid-time: 600
    allow-credentials: true
    origins: http://localhost:8765
  cache:
    default-cache: local
    impl:
      local: xyz.ytora.base.cache.support.local.CacheByLocal
  sql4j:
    entity-path: xyz.ytora
    repo-path: xyz.ytora
    sql-log-impl: xyz.ytora.base.sql4J.MySqlLogger
    create-table-if-not-exist: true
    dynamic-ds:
      primary:
        #连接基本信息
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ytora?currentSchema=ytora&ssl=false
        username: ytora
        password: 220600
        type: com.zaxxer.hikari.HikariDataSource
